[package]
name = "finetime"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Quinten-van-Woerkom/finetime"

[features]
default = ["std"]
std = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }

[target.'cfg(kani)'.dependencies]
paste = "1.0.15"

[dependencies]
lazy_static = "1.5.0"
num = "0.4.3"
tinyvec = "1.9.0"

[build-dependencies]
ureq = "2"
